# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93b1ab4ee8c678a497b4a641cdf8230d55074735bc94ff39818cf37c2481ac0e818546ed4703e087c0aa481a35d404d8fdd755ab87087d842708d48f151ada9f

test:
  secret_key_base: 77ad4509424698f959a14059bf9aecef4409ee4b90a332263f656c6fd9b2c097234e89f4e0735b9a17810aa65896c93484638e2f336e57b21e58ff4195676863

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
